# Generated by Django 4.2.2 on 2023-07-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.ImageField(default=None, upload_to=None),
            preserve_default=False,
        ),
    ]
