# Generated by Django 4.2.2 on 2023-07-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_products_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
