# Generated by Django 4.2.2 on 2023-07-29 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.type'),
            preserve_default=False,
        ),
    ]
