# Generated by Django 4.2.2 on 2023-08-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
